[2022-02-18 13:14:02,158] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: matchup.enter_virtual_env 2022-02-18T13:13:59.355148+00:00 [queued]>
[2022-02-18 13:14:02,168] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: matchup.enter_virtual_env 2022-02-18T13:13:59.355148+00:00 [queued]>
[2022-02-18 13:14:02,168] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-02-18 13:14:02,168] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2022-02-18 13:14:02,168] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-02-18 13:14:02,179] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): enter_virtual_env> on 2022-02-18T13:13:59.355148+00:00
[2022-02-18 13:14:02,183] {standard_task_runner.py:52} INFO - Started process 248 to run task
[2022-02-18 13:14:02,189] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'matchup', 'enter_virtual_env', '2022-02-18T13:13:59.355148+00:00', '--job-id', '6', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/matchup.py', '--cfg-path', '/tmp/tmp22ah1vvn', '--error-file', '/tmp/tmpcx4u9aqm']
[2022-02-18 13:14:02,190] {standard_task_runner.py:77} INFO - Job 6: Subtask enter_virtual_env
[2022-02-18 13:14:02,222] {logging_mixin.py:104} INFO - Running <TaskInstance: matchup.enter_virtual_env 2022-02-18T13:13:59.355148+00:00 [running]> on host 531edfb863fc
[2022-02-18 13:14:02,253] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=r.chesne@gmail.com
AIRFLOW_CTX_DAG_OWNER=Robin
AIRFLOW_CTX_DAG_ID=matchup
AIRFLOW_CTX_TASK_ID=enter_virtual_env
AIRFLOW_CTX_EXECUTION_DATE=2022-02-18T13:13:59.355148+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-18T13:13:59.355148+00:00
[2022-02-18 13:14:02,254] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-02-18 13:14:02,255] {bash.py:158} INFO - Running command: . /app/env/bin/activate
[2022-02-18 13:14:02,263] {bash.py:169} INFO - Output:
[2022-02-18 13:14:02,269] {bash.py:177} INFO - Command exited with return code 0
[2022-02-18 13:14:02,296] {taskinstance.py:1159} INFO - Marking task as SUCCESS. dag_id=matchup, task_id=enter_virtual_env, execution_date=20220218T131359, start_date=20220218T131402, end_date=20220218T131402
[2022-02-18 13:14:02,324] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-02-18 13:14:02,359] {local_task_job.py:146} INFO - Task exited with return code 0
