[2022-03-18 00:00:02,354] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: matchup.enter_virtual_env 2022-03-17T18:00:00+00:00 [queued]>
[2022-03-18 00:00:02,360] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: matchup.enter_virtual_env 2022-03-17T18:00:00+00:00 [queued]>
[2022-03-18 00:00:02,360] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-03-18 00:00:02,360] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2022-03-18 00:00:02,360] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-03-18 00:00:02,373] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): enter_virtual_env> on 2022-03-17T18:00:00+00:00
[2022-03-18 00:00:02,377] {standard_task_runner.py:52} INFO - Started process 390190 to run task
[2022-03-18 00:00:02,382] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'matchup', 'enter_virtual_env', '2022-03-17T18:00:00+00:00', '--job-id', '363', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/matchup.py', '--cfg-path', '/tmp/tmplj7fetg2', '--error-file', '/tmp/tmp1e6bj94y']
[2022-03-18 00:00:02,382] {standard_task_runner.py:77} INFO - Job 363: Subtask enter_virtual_env
[2022-03-18 00:00:02,424] {logging_mixin.py:104} INFO - Running <TaskInstance: matchup.enter_virtual_env 2022-03-17T18:00:00+00:00 [running]> on host 531edfb863fc
[2022-03-18 00:00:02,460] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=r.chesne@gmail.com
AIRFLOW_CTX_DAG_OWNER=Robin
AIRFLOW_CTX_DAG_ID=matchup
AIRFLOW_CTX_TASK_ID=enter_virtual_env
AIRFLOW_CTX_EXECUTION_DATE=2022-03-17T18:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-17T18:00:00+00:00
[2022-03-18 00:00:02,461] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-03-18 00:00:02,462] {bash.py:158} INFO - Running command: . /app/env/bin/activate
[2022-03-18 00:00:02,479] {bash.py:169} INFO - Output:
[2022-03-18 00:00:02,493] {bash.py:177} INFO - Command exited with return code 0
[2022-03-18 00:00:02,514] {taskinstance.py:1159} INFO - Marking task as SUCCESS. dag_id=matchup, task_id=enter_virtual_env, execution_date=20220317T180000, start_date=20220318T000002, end_date=20220318T000002
[2022-03-18 00:00:02,535] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-18 00:00:02,552] {local_task_job.py:146} INFO - Task exited with return code 0
