[2022-03-29 12:00:02,536] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: matchup.enter_virtual_env 2022-03-29T06:00:00+00:00 [queued]>
[2022-03-29 12:00:02,542] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: matchup.enter_virtual_env 2022-03-29T06:00:00+00:00 [queued]>
[2022-03-29 12:00:02,542] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-03-29 12:00:02,542] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2022-03-29 12:00:02,542] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-03-29 12:00:02,548] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): enter_virtual_env> on 2022-03-29T06:00:00+00:00
[2022-03-29 12:00:02,552] {standard_task_runner.py:52} INFO - Started process 554031 to run task
[2022-03-29 12:00:02,555] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'matchup', 'enter_virtual_env', '2022-03-29T06:00:00+00:00', '--job-id', '545', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/matchup.py', '--cfg-path', '/tmp/tmpm9pfkou2', '--error-file', '/tmp/tmpfcm9f4l3']
[2022-03-29 12:00:02,556] {standard_task_runner.py:77} INFO - Job 545: Subtask enter_virtual_env
[2022-03-29 12:00:02,586] {logging_mixin.py:104} INFO - Running <TaskInstance: matchup.enter_virtual_env 2022-03-29T06:00:00+00:00 [running]> on host 531edfb863fc
[2022-03-29 12:00:02,610] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=r.chesne@gmail.com
AIRFLOW_CTX_DAG_OWNER=Robin
AIRFLOW_CTX_DAG_ID=matchup
AIRFLOW_CTX_TASK_ID=enter_virtual_env
AIRFLOW_CTX_EXECUTION_DATE=2022-03-29T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-29T06:00:00+00:00
[2022-03-29 12:00:02,611] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-03-29 12:00:02,612] {bash.py:158} INFO - Running command: . /app/env/bin/activate
[2022-03-29 12:00:02,620] {bash.py:169} INFO - Output:
[2022-03-29 12:00:02,625] {bash.py:177} INFO - Command exited with return code 0
[2022-03-29 12:00:02,640] {taskinstance.py:1159} INFO - Marking task as SUCCESS. dag_id=matchup, task_id=enter_virtual_env, execution_date=20220329T060000, start_date=20220329T120002, end_date=20220329T120002
[2022-03-29 12:00:02,659] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-29 12:00:02,686] {local_task_job.py:146} INFO - Task exited with return code 0
